root: true
parser: babel-eslint
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  strict:
    - error
    - safe
  standard/computed-property-even-spacing: false
overrides:
  - files:
      - index.js
      - bin/gnostic.js
      - test/setup.js
      - .mocharc.js
    excludedFiles:
      - '**/index.js'
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
