extends:
  - semistandard
  - 'plugin:prettier/recommended'
  - 'plugin:import/errors'
  - 'plugin:monorepo/recommended'
overrides:
  - files:
      - .mocharc.js
    parserOptions:
      sourceType: script
  - env:
      mocha: true
    files:
      - '**/test/**/*.spec.js'
    globals:
      expect: false
      proxyquire: false
      sinon: false
    rules:
      no-restricted-syntax:
        - error
        - selector: "Program > ExpressionStatement > CallExpression[callee.name=describe] > Literal:not([raw=/^'@report-toolkit\\u002F\\S+?(:\\S+)*'/])"
          message: 'Top-level describe() must be of format "@report-toolkit/<package>" or "@report-toolkit/<package>:<module>[:module...]"'
      monorepo/no-internal-import: 0
parser: babel-eslint
plugins:
  - simple-import-sort
root: true
rules:
  import/exports-last: error
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/order: 0
  no-restricted-syntax:
    - error
    - selector: 'CallExpression[callee.name=Symbol] > Literal:not([value=/^report-toolkit-[a-z-]+$/])'
      message: 'Symbol() must be called with a kebab-case description beginning with  "report-toolkit-"'
  simple-import-sort/sort: error
  sort-imports: 0
  standard/computed-property-even-spacing: 0
  strict:
    - error
    - safe
