name: Node CI

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm test
  mirror:
    name: Mirror to GHE
    runs-on: ubuntu-latest
    steps:
      - uses: boneskull/mirror-action@mirror-mode
        with:
          args: 'https://github.ibm.com/Christopher-Hiller/report-toolkit.git'
          secrets: GIT_PASSWORD
          env: "GIT_USERNAME='Christopher-Hiller'"
